### ISSUE TITLE
Workflow to Manage Image processing

### ISSUE THREAD

**Issue by saurabhd** [narendra-addweb/MyImmoPix#125]
PFA Doc to manage image process and delivery with notification at every stage.

Let me know your kind thoughts. 
[Workflow_8th March.pdf](https://github.com/narendra-addweb/MyImmoPix/files/163173/Workflow_8th.March.pdf)

**Comment by saurabhd** [comment]
PFA Doc for Approach. 

[Approach_9th March.pdf](https://github.com/narendra-addweb/MyImmoPix/files/165330/Approach_9th.March.pdf)

**Comment by Krina-Addweb** [comment]
Issues & Query which were founded during testing : 
1) Spelling mistake of "Origional" to "Original"
2) Project status should be "Close" to "Closed"
3) Query : Multiple uploaded images are displaying in folder 
4) For all Thumbnail images,it should display full image instead of displaying cut.
5) Fix the size of download image.

**Comment by narendra-addweb** [comment]
Please find Imageprocessing.docx
[Imageprocessing.docx](https://github.com/narendra-addweb/MyImmoPix/files/212386/Imageprocessing.docx)
 for Image processing step by step documentation.
