### ISSUE TITLE
Language specific : Footer 

### ISSUE THREAD

**Issue by Krina-Addweb** [narendra-addweb/MyImmoPix#132]
Footer Links Needs for page in different languages also, right now the pages are available in English language only.

**Comment by Maxfavier** [comment]
There are one item in both French and Dutch that is not aligned the same way (text is centered instead of aligned to the left).

<img width="195" alt="capture d ecran 2016-03-16 14 45 37" src="https://cloud.githubusercontent.com/assets/17143257/13814265/dc71557c-eb85-11e5-82b6-721f028e8104.png">
<img width="156" alt="capture d ecran 2016-03-16 14 45 26" src="https://cloud.githubusercontent.com/assets/17143257/13814268/df4ea6f0-eb85-11e5-95ea-de7937433d42.png">
