### ISSUE TITLE
Video for the French home page

### ISSUE THREAD

**Issue by Maxfavier** [narendra-addweb/MyImmoPix#137]
There exists a video in French to include for the French home page (replacing the current one in ENG).
(For Dutch page, the ENG video will do fine).

I'll post it over Skype

**Comment by Krina-Addweb** [comment]
Can you please upload the given video on youtube so that we can get the respective link?

**Comment by Maxfavier** [comment]
Here's the link.
However, I did not put it public; I'm not too happy with that solution.
Would it work still ?
If not is there another way ?

https://www.youtube.com/watch?v=S30PlMheqj8&feature=youtu.be

**Comment by narendra-addweb** [comment]
You need to set your videos to "unlisted" instead of "private" OR "public". That way the video does not show up on your channel or on any search results and we can embed the video on our site.

_NOTE_: If anyone have the direct link to the video can see it.

See how to setup your video as "Unlisted" from [here](https://support.google.com/youtube/answer/157177). 

Let me know if this solution works for you.

**Comment by Maxfavier** [comment]
Hello,

It's done thank you.

https://youtu.be/S30PlMheqj8

Regards,

Maxime

2016-03-22 7:49 GMT+01:00 narendra-addweb notifications@github.com:

**Comment by narendra-addweb** [comment]
Thanks for the video Maxime. Would also require the video for English and Dutch languages.

**Comment by Maxfavier** [comment]
Here's the English one.
For the Dutch, please use the English version.

https://youtu.be/EZNL-fOlYWE
