### ISSUE TITLE
PDF Homepage T.A.b:

### ISSUE THREAD

**Issue by Krina-Addweb** [narendra-addweb/MyImmoPix#42]
T.A.b: The page should open up in the language identified form the language preferences of
the user's browser.

**Comment by Maxfavier** [comment]
Please let me know how I can test this. Thank you

**Comment by saurabhd** [comment]
We have provided Language specific dropdown at Footer section. You can select respective language and check the according content changes for the Homepage.

**Comment by Maxfavier** [comment]
This issue is about opening the website in the right language when a user arrives for the first time on the website. For instance, if I'm in Paris, using my computer, I should land directly on the site in French version.
That is what I would like to test if this issue is closed. I hope this issue was correctly interpreted.
Thank you

I noticed that the language bar in the footer is working perfectly though.

**Comment by narendra-addweb** [comment]
_How functionality work​_
1. Site open into country region language based on geoip google api functionality(For instance, if I'm in Paris, using my computer, I should land directly on the site in French version.)
2. User can change his/her language by navigating from footer language selector.
3. I use cookie(Expire after 1 month) for store user language, within 1 month if user open again this site then it will open into previously selected language.

**Comment by Maxfavier** [comment]
Perfect, thanks !
